
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author DELL
 */
public class Billing extends javax.swing.JFrame {
    public double finalTotall=0;

    /**
     * Creates new form Billing
     */
    public Billing() {
        initComponents();
        SimpleDateFormat Fdate = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        datelabel.setText(Fdate.format(date));
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH-mm-ss");
        LocalDateTime ldt = LocalDateTime.now();
        timelabel.setText(dtf.format(ldt));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        datelabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        timelabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        contactfield = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        addressfield = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        idfield = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        productnamefield = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ratefield = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        quilityfield = new javax.swing.JTextField();
        addbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        totallfield = new javax.swing.JTextField();
        totallamount = new javax.swing.JTextField();
        returnamountfield = new javax.swing.JTextField();
        resetbutton = new javax.swing.JButton();
        closeebutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        diiscountfield = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        printbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Billing ani.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 13, -1, 135));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billing.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 25, -1, -1));

        datelabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        datelabel.setText("jLabel4");
        getContentPane().add(datelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 26, 100, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Time");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(769, 68, -1, -1));

        timelabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        timelabel.setText("jLabel6");
        getContentPane().add(timelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 69, 80, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Buyer Details");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 153, 131, 31));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 215, -1, -1));

        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });
        getContentPane().add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 213, 125, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Contact No");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 215, -1, -1));
        getContentPane().add(contactfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 213, 165, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 215, -1, -1));
        getContentPane().add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 213, 168, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Address");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(778, 215, -1, -1));
        getContentPane().add(addressfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 213, 138, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Product Details");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 273, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Product ID");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 324, -1, -1));

        idfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idfieldActionPerformed(evt);
            }
        });
        getContentPane().add(idfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 322, 74, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Product Name");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 324, -1, -1));
        getContentPane().add(productnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 322, 137, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Rate");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 324, -1, -1));
        getContentPane().add(ratefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 322, 72, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Quantity");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(813, 324, -1, -1));
        getContentPane().add(quilityfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(903, 322, 87, -1));

        addbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addbutton.setText("Add");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(addbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(929, 378, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Rate", "Quantity", "discount", "Totall"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 418, 518, 302));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Calculation Details");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 418, -1, 35));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Total");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 490, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Paid Amount");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 554, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Return Amount");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 615, -1, -1));
        getContentPane().add(totallfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 484, 167, 40));

        totallamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totallamountActionPerformed(evt);
            }
        });
        getContentPane().add(totallamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 542, 167, 43));

        returnamountfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnamountfieldActionPerformed(evt);
            }
        });
        getContentPane().add(returnamountfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 603, 168, 42));

        resetbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resetbutton.setText("Reset");
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(resetbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(934, 550, -1, -1));

        closeebutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        closeebutton.setText("Close");
        closeebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(closeebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(936, 611, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Discount");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 324, -1, -1));
        getContentPane().add(diiscountfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 322, 86, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));

        printbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        printbutton.setText("Print");
        printbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(935, Short.MAX_VALUE)
                .addComponent(printbutton)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(482, Short.MAX_VALUE)
                .addComponent(printbutton)
                .addGap(298, 298, 298))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idfieldActionPerformed
        // TODO add your handling code here:
        String pid = idfield.getText();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/billingg", "root", "");
            
            Statement st = con.createStatement();
            ResultSet rs;
            rs = st.executeQuery("select * from product_information where  Product_Id like'" + pid + "%'");
            if (rs.next()) {
                idfield.setText(rs.getString(3));
                productnamefield.setText(rs.getString(1));
                ratefield.setText(rs.getString(2));
                diiscountfield.setText(rs.getString(4 ));
                quilityfield.setText("1");
                
            } else {
                productnamefield.setText(rs.getString(""));
                ratefield.setText(rs.getString(""));
                
                quilityfield.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        

    }//GEN-LAST:event_idfieldActionPerformed

    private void returnamountfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnamountfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnamountfieldActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        // TODO add your handling code here:
        double price = Double.parseDouble(ratefield.getText());
        double quintity= Double.parseDouble(quilityfield.getText());
        int discount=Integer.parseInt(diiscountfield.getText());
        double totall=(price*quintity)*discount/100;
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
   
        model.addRow(new Object[]{productnamefield.getText(),price,quintity,discount,totall});
        finalTotall =finalTotall+totall;
        String finalTotal=String.valueOf(finalTotall);
        totallfield.setText(finalTotal);
    }//GEN-LAST:event_addbuttonActionPerformed

    private void closeebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeebuttonActionPerformed
        // TODO add your handling code here:
         int a = JOptionPane.showConfirmDialog(null, "Do you want to really close the application", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            dispose();
            setVisible(false);
            new Home().setVisible(true);
        }
    }//GEN-LAST:event_closeebuttonActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, " Reset this application", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new Billing().setVisible(true);
        }
    }//GEN-LAST:event_resetbuttonActionPerformed

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
        String name = namefield.getText();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/billingg", "root", "");
            
            Statement st = con.createStatement();
            ResultSet rs;
            rs = st.executeQuery("select * from user_data where Name like'" + name + "%'");
            if (rs.next()) {
                namefield.setText(rs.getString(1));
                contactfield.setText(rs.getString(2));
                emailfield.setText(rs.getString(3));
                
                addressfield.setText(rs.getString(4));
                
            } else {
                contactfield.setText(rs.getString(""));
                emailfield.setText(rs.getString(""));
                
                addressfield.setText(rs.getString(""));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_namefieldActionPerformed

    private void totallamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totallamountActionPerformed
        // TODO add your handling code here:
        String paid_amount=totallamount.getText();
        int PAM=Integer.parseInt(paid_amount);
       finalTotall=PAM-finalTotall;
       String finalTotal=String.valueOf(finalTotall);
        returnamountfield.setText(finalTotal);
        //returnamountfield.setEnabled(false);
    }//GEN-LAST:event_totallamountActionPerformed

    private void printbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbuttonActionPerformed
        // TODO add your handling code here:
        try {
            jTable1.print(JTable.PrintMode.NORMAL);
        } catch (Exception a) {
            JOptionPane.showMessageDialog(null, a);
        }
    }//GEN-LAST:event_printbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JTextField addressfield;
    private javax.swing.JButton closeebutton;
    private javax.swing.JTextField contactfield;
    private javax.swing.JLabel datelabel;
    private javax.swing.JTextField diiscountfield;
    private javax.swing.JTextField emailfield;
    private javax.swing.JTextField idfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField namefield;
    private javax.swing.JButton printbutton;
    private javax.swing.JTextField productnamefield;
    private javax.swing.JTextField quilityfield;
    private javax.swing.JTextField ratefield;
    private javax.swing.JButton resetbutton;
    private javax.swing.JTextField returnamountfield;
    private javax.swing.JLabel timelabel;
    private javax.swing.JTextField totallamount;
    private javax.swing.JTextField totallfield;
    // End of variables declaration//GEN-END:variables
}
