
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jMenu1 = new javax.swing.JMenu();
        updatebuyerbutton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        productdetailsbutton = new javax.swing.JButton();
        newproductbutton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        delateproductbutton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        newbuyerbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        updateproducbutton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        logoutbutton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buyerdetailsbutton = new javax.swing.JButton();
        delatebuyerbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        billingbutton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        closebutton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1336, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updatebuyerbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatebuyerbutton.setText("Update buyer");
        updatebuyerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuyerbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(updatebuyerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 130, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_20210104_112758.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1160, -1230, -1, 640));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productdetailsbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        productdetailsbutton.setText("Product  details");
        productdetailsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productdetailsbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(productdetailsbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, -1, -1));

        newproductbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newproductbutton.setText("New product");
        newproductbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newproductbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(newproductbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new product.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        delateproductbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delateproductbutton.setText("Delate product");
        delateproductbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delateproductbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(delateproductbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete product.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details product.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, -1, -1));

        newbuyerbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newbuyerbutton.setText("New buyer");
        newbuyerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbuyerbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(newbuyerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new buyer.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 75, -1));

        updateproducbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateproducbutton.setText("Update product");
        updateproducbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateproducbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(updateproducbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update product.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        logoutbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutbutton.setText("Log out");
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(logoutbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 110, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 10, 75, 74));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buyer Details.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Update buyer.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        buyerdetailsbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buyerdetailsbutton.setText("Buyer details");
        buyerdetailsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyerdetailsbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(buyerdetailsbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, -1));

        delatebuyerbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delatebuyerbutton.setText("Delate Buyer");
        delatebuyerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delatebuyerbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(delatebuyerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete buyer.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, -1));

        billingbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        billingbutton.setText("Billings");
        billingbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(billingbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 110, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billing.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, -1, -1));

        closebutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        closebutton.setText("Close");
        closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebuttonActionPerformed(evt);
            }
        });
        jPanel2.add(closebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 110, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 10, 1480, 660));

        jMenuBar1.add(jMenu3);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newbuyerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbuyerbuttonActionPerformed
        // TODO add your handling code here:
        dispose();
        new NewBuyer().setVisible(true);
    }//GEN-LAST:event_newbuyerbuttonActionPerformed

    private void updatebuyerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuyerbuttonActionPerformed
        // TODO add your handling code here:
        dispose();
        new UpdateBuyer().setVisible(true);
     
    }//GEN-LAST:event_updatebuyerbuttonActionPerformed

    private void newproductbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newproductbuttonActionPerformed
        // TODO add your handling code here:
        dispose();
        new NewProduct().setVisible(true);
    }//GEN-LAST:event_newproductbuttonActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "Do you really logout this aplication","Selected",JOptionPane.YES_NO_OPTION);
        if(a==0){
            dispose();
            setVisible(false);
            new LogIn().setVisible(true);
        }
    }//GEN-LAST:event_logoutbuttonActionPerformed

    private void closebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebuttonActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "Do you really close this aplication","Selected",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_closebuttonActionPerformed

    private void buyerdetailsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyerdetailsbuttonActionPerformed
        // TODO add your handling code here:
        dispose();
        new BuyerDetails().setVisible(true);
    }//GEN-LAST:event_buyerdetailsbuttonActionPerformed

    private void delatebuyerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delatebuyerbuttonActionPerformed
        // TODO add your handling code here:
        dispose();
        new DeleteBuyer().setVisible(true);
    }//GEN-LAST:event_delatebuyerbuttonActionPerformed

    private void updateproducbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateproducbuttonActionPerformed
        // TODO add your handling code here:
        dispose();
        new UpdateProduct().setVisible(true);
    }//GEN-LAST:event_updateproducbuttonActionPerformed

    private void productdetailsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productdetailsbuttonActionPerformed
        // TODO add your handling code here:
        dispose();
        new ProductDetails().setVisible(true);
    }//GEN-LAST:event_productdetailsbuttonActionPerformed

    private void delateproductbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delateproductbuttonActionPerformed
        // TODO add your handling code here:
        dispose();
        new DeleteProduct().setVisible(true);
    }//GEN-LAST:event_delateproductbuttonActionPerformed

    private void billingbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingbuttonActionPerformed
        // TODO add your handling code here:
        dispose();
        new Billing().setVisible(true);
    }//GEN-LAST:event_billingbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton billingbutton;
    private javax.swing.JButton buyerdetailsbutton;
    private javax.swing.JButton closebutton;
    private javax.swing.JButton delatebuyerbutton;
    private javax.swing.JButton delateproductbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton newbuyerbutton;
    private javax.swing.JButton newproductbutton;
    private javax.swing.JButton productdetailsbutton;
    private javax.swing.JButton updatebuyerbutton;
    private javax.swing.JButton updateproducbutton;
    // End of variables declaration//GEN-END:variables
}
